[MIG] event_registration_mass_mailing: Migration to 11.0
OCA/event pull request #114
Opened 2018-07-10 14:33 UTC by chienandalu

This module adds actions to send mass mailings and allows to add to mailing
lists from event registrations tree view.

cc @Tecnativa

2018-07-11 06:53 UTC, yajo approved these changes

2018-07-11 11:47 UTC, pedrobaeza requested changes

2018-07-11 11:47 UTC, pedrobaeza commented on event_registration_mass_mailing/__manifest__.py
>          'mass_mailing'
Depend on new `mass_mailing_event` instead

2018-07-11 11:47 UTC, pedrobaeza commented on event_registration_mass_mailing/README.rst
> -.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Can you please try to generate the README for not having such a big diff?

2018-07-11 12:12 UTC, chienandalu commented
@pedrobaeza Done

2018-08-06 06:34 UTC, chienandalu commented
@pedrobaeza All comment were attended here

2018-08-06 09:25 UTC, pedrobaeza approved these changes

2018-08-06 09:28 UTC, merged