[12.0][MIG] website_event_filter_selector: Migration to v12
OCA/event pull request #131
Opened 2019-03-01 16:55 UTC by cristinamartinrod

cc @Tecnativa

2019-03-04 10:09 UTC, pedrobaeza commented
Tests are not correct.

2019-03-07 11:59 UTC, yajo requested changes
There's one change to do. I'm not sure if it will fix travis...

2019-03-07 11:59 UTC, Yajo commented on website_event_filter_selector/tests/test_ui.py
> +            env = self.env(cr)
This hack is no longer needed in v12. Remove the `with` block and use `self.env` instead of `env`.

2019-03-07 11:59 UTC, Yajo commented on website_event_filter_selector/__manifest__.py
> +    # ],
:fire: remove this.

2019-03-07 12:22 UTC, rafaelbn commented
@cristinamartinrod travis is :red_circle: because:

```
2019-03-04 12:15:46,089 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: FAIL
2019-03-04 12:15:46,089 6475 INFO openerp_test odoo.addons.website_event_filter_selector.tests.test_ui.UICase: Closing chrome headless with pid 6492
2019-03-04 12:15:46,090 6475 INFO openerp_test odoo.addons.website_event_filter_selector.tests.test_ui.UICase: Terminating chrome headless with pid 6492
2019-03-04 12:15:46,101 6475 INFO openerp_test odoo.addons.website_event_filter_selector.tests.test_ui.UICase: Removing chrome user profile "/tmp/tmph2r37vb4_chrome_odoo"
2019-03-04 12:15:46,102 6475 INFO openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: ======================================================================
2019-03-04 12:15:46,102 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: FAIL: test_ui_website (odoo.addons.website_event_filter_selector.tests.test_ui.UICase)
2019-03-04 12:15:46,102 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: ` Test frontend tour.
2019-03-04 12:15:46,103 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: Traceback (most recent call last):
2019-03-04 12:15:46,103 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: `   File "/home/travis/build/OCA/event/website_event_filter_selector/tests/test_ui.py", line 48, in test_ui_website
2019-03-04 12:15:46,103 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: `     ready="odoo.__DEBUG__.services['web_tour.tour']"
2019-03-04 12:15:46,103 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: `   File "/home/travis/odoo-12.0/odoo/tests/common.py", line 923, in browser_js
2019-03-04 12:15:46,103 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: `     self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
2019-03-04 12:15:46,104 6475 ERROR openerp_test odoo.addons.website_event_filter_selector.tests.test_ui: ` AssertionError: False is not true : The ready "odoo.__DEBUG__.services['web_tour.tour'].tours.website_event_filter_selector.ready" code was always falsy
```

2019-03-08 12:05 UTC, Yajo commented
Right now tests are failing. See: https://travis-ci.org/OCA/event/jobs/503523853#L1537
Possibly you need to modify the tour.

2019-04-16 09:47 UTC, yajo approved these changes
Tests fixed.

2019-04-16 11:20 UTC, pedrobaeza approved these changes

2019-04-16 11:21 UTC, merged