[12.0][MIG] event_track_location_overlap: Migration to v12
OCA/event pull request #132
Opened 2019-03-05 12:29 UTC by cristinamartinrod

cc @Tecnativa

2019-03-05 12:42 UTC, yajo requested changes
Please squash those `!fixup` commits.

2019-03-05 12:42 UTC, Yajo commented on event_track_location_overlap/README.rst
> +  * Cristina Martin R.
No need to add this if you split the README. It will be added on next autogeneration by bot.

2019-03-05 15:21 UTC, pedrobaeza requested changes

2019-03-05 15:21 UTC, pedrobaeza commented on event_track_location_overlap/models/event_track_location.py
> +    @api.one  # pragma pylint: disable=api-one-deprecated
Change this to multi-record approach.

2019-03-05 15:21 UTC, pedrobaeza commented on event_track_location_overlap/models/event_track_location.py
> +            ("state", "not in", skip_track_states),
This field is no more in `event.track` model. Put `("event_id.state", "not in", ...`

2019-03-05 15:21 UTC, pedrobaeza commented on event_track_location_overlap/models/event_track_location.py
> +            a_start = fields.Datetime.from_string(a_track.date)
These are already dates, so remove the conversions

2019-03-05 15:21 UTC, pedrobaeza commented on setup/_metapackage/VERSION.txt
> +12.0.20190304.0
Why these changes?

2019-03-07 11:30 UTC, yajo requested changes
Do a proper rebase please.

2019-03-08 12:00 UTC, yajo requested changes
Also, please:

1. remove commit adb72fcdcae69595e83b6beaac7eafa3a15d4dce
1. remove commit 7a26a1e732622dfda551997c20babb108a31c740

2019-03-08 12:00 UTC, yajo commented on event_track_location_overlap/models/event_track_location.py
> +            ("event_id.state", "not in", skip_track_states),
Sorry I know you were asked to put this here, but it is wrong. :roll_eyes: 

The idea behind this code is that if you have i.e. 2 tracks in draft that overlap, it shouldn't be a problem. You can still approve one and cancel the other one.

In Odoo v12, event tracks have a new field: `stage_id`, which leads to a new model: `event.track.stage`. This new model has a new boolean called `is_done`, so this logic has to change a little bit and adapt to that.

2019-03-08 12:00 UTC, yajo commented on setup/_metapackage/VERSION.txt
> +12.0.20190304.0
Exclude this file from the commit please.

2019-03-08 12:00 UTC, yajo commented on event_track_location_overlap/models/event_track_location.py
> +    @api.multi  # pragma pylint: disable=api-one-deprecated
This strange comment is here to give an instruction to the linter. Remove it, now that it's changed.

2019-04-08 16:48 UTC, victormmtorres commented on event_track_location_overlap/models/event_track_location.py
> +            ("state", "not in", skip_track_states),
It looks like `state` does not exist on the model's field definition

2019-04-16 12:58 UTC, yajo approved these changes
All comments attended, it should go :heavy_check_mark: now.

2019-04-18 11:36 UTC, pedrobaeza approved these changes

2019-04-18 11:36 UTC, merged