[11.0][MIG] website event require login
OCA/event pull request #142
Opened 2019-04-08 19:42 UTC by Change2improve

2019-04-09 07:17 UTC, chienandalu requested changes
Looks like your editor is messing the changes up :confused:

2019-04-11 21:42 UTC, emagdalenaC2i commented
Yes, the day I finally quit MS Visual Studio I'll open my best bottle of champagne, but as long as I continue programming for SolidWorks, I have no choice to change. 
Maybe I could try MS Visual Studio Code for Odoo, I have to try it more thoroughly.

Some time ago I created a PR to add those files to gitignore https://github.com/OCA/maintainer-tools/pull/316 (it is approved and merged) and it has been moved to other repositories like OCA / project where I usually collaborate more. But it has not been extended to the rest of the OCA repositories.

2019-04-12 01:40 UTC, daramousk commented on website_event_require_login/models/event.py
> +        default=False,
The `default=False` is not really needed here as explained in https://github.com/OCA/OCB/blob/11.0/odoo/models.py#L2144

2019-04-12 01:40 UTC, daramousk commented on website_event_require_login/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/199/10.0
I think this needs to be generated again since links from 10.0 remain.

2019-05-10 07:58 UTC, chienandalu requested changes
Please, @Change2improve, get rid of those ` .vs/*` files so this can be approved :+1:

2019-05-10 08:55 UTC, emagdalenaC2i commented
@chienandalu done

2019-05-10 12:18 UTC, chienandalu approved these changes
Great, thanks!

2019-05-10 13:59 UTC, merged