[MIG] website_event_questions_template: Migration to 12.0
OCA/event pull request #152
Opened 2019-06-03 17:07 UTC by victormmtorres

cc @Tecnativa

2019-06-03 17:25 UTC, victormmtorres commented
@sergio-teruel Please have a check

2019-06-03 17:26 UTC, pedrobaeza requested changes
We used the trick of loading the questions in v10 with a button because there were no proper support for onchanges in nested one2many, but now I think the support is correct. Can you please switch back to fill things in onchange for not needing to save + press button?

2019-06-03 17:27 UTC, pedrobaeza commented
Other minor thing is that a field with a number that I suppose is the sequence is shown when defining the question template.

2019-06-03 17:33 UTC, victormmtorres commented
I will refactor based on your comments @pedrobaeza

2019-06-20 14:31 UTC, victormmtorres commented
@pedrobaeza I pushed a new WIP commit so you could test if could work onchage option

2019-06-24 16:45 UTC, victormmtorres commented
>Other minor thing is that a field with a number that I suppose is the sequence is shown when defining the question template.

@pedrobaeza I removed the previous commit, here is the reason https://github.com/odoo/odoo/issues/20163#issuecomment-505055793

2019-06-27 17:00 UTC, pedrobaeza requested changes

2019-06-27 17:00 UTC, pedrobaeza commented on website_event_questions_template/models/event_question_template.py
> +# Copyright 2017-2019 Tecnativa - Sergio Teruel
Sergio hasn't done anything in 2019, so you shouldn't change its copyright. In any case, yours should be added in 2019, but any way, this file hasn't been modified, so you don't have to change whole copyright. This applies to all the files incorrectly modified.

2019-06-27 17:00 UTC, pedrobaeza commented on website_event_questions_template/readme/CONTRIBUTORS.rst
> +
Add you as contributor

2019-06-27 17:32 UTC, victormmtorres commented
Changes done @pedrobaeza

2019-06-27 17:34 UTC, pedrobaeza commented on website_event_questions_template/views/event_view.xml
> +<!-- Copyright 2017-2019 Tecnativa - Sergio Teruel
This still remains

2019-06-27 17:34 UTC, pedrobaeza commented on website_event_questions_template/views/website_event_questions_template_view.xml
> +<!-- Copyright 2017-2019 Tecnativa - Sergio Teruel
This still remains

2019-06-27 17:37 UTC, victormmtorres commented
Changes done @pedrobaeza

2019-06-27 17:38 UTC, pedrobaeza approved these changes

2019-06-28 07:19 UTC, sergio-teruel approved these changes

2019-06-28 07:24 UTC, pedrobaeza commented
/ocabot merge

2019-06-28 07:42 UTC, merged