[13.0][MIG] website_event_filter_selector: Migration to 13.0
OCA/event pull request #208
Opened 2021-02-26 09:48 UTC by victoralmau

Migration to 13.0

Please @Yajo and @pedrobaeza can you review it?

@Tecnativa TT27591

2021-03-02 19:55 UTC, pedrobaeza requested changes
Please squash some administrative commits and change readme according the remaining feature (adding the city dropdown). You can rename the module if you think it fits better.

2021-03-03 07:16 UTC, victoralmau commented
Readme information is changed although `readme.rst` file is not change because bot will be regenerate it in merge process right?
Too, IMO addon it's need to rename to `website_event_city_filter` what do you think about it?

2021-03-07 02:45 UTC, pedrobaeza commented
Following the usual structure, better to be named `website_event_filter_city`, as we don't have to be English order correct, but "drill-through" correct.

2021-03-08 08:15 UTC, Yajo commented
Could you post some screenshots? runbot doesn't work

2021-03-08 08:20 UTC, Yajo commented on website_event_filter_selector/controllers/main.py
> -                    )
I think that, by removing these lines, you're introducing a bug.

At least in previous versions, when you filtered by one criteria, other criterias' counters were updated accordingly.

Example:

1. I have 2 Trainings in Spain and 2 trainings in France.
2. "All types" displays count 4️⃣ 
3. I filter by country=France
4. "All types" displays count 2️⃣ 

The same should apply to the cities filter here.

2021-03-08 08:20 UTC, Yajo requested changes

2021-03-08 08:20 UTC, Yajo commented on website_event_filter_selector/readme/CONTRIBUTORS.rst
> +    * Jairo Llopiso
```suggestion
    * Jairo Llopis
```

2021-03-08 08:54 UTC, victoralmau commented on website_event_filter_selector/readme/CONTRIBUTORS.rst
> +    * Jairo Llopiso
Sorry!!

2021-03-08 09:44 UTC, victoralmau commented
Addon changed to website_event_filter_city.
Screenshot  added.
Improve controller to keep domain search and list only cities related to events listed.

2021-03-08 10:06 UTC, Yajo requested changes
I'm afraid the problem from https://github.com/OCA/event/pull/208#discussion_r589239929 still happens.

Just check this out:

![imagen](https://user-images.githubusercontent.com/973709/110305657-d5c2e700-7ff4-11eb-8c07-8a9db4125949.png)

![imagen](https://user-images.githubusercontent.com/973709/110305957-2fc3ac80-7ff5-11eb-8fb6-90824111740f.png)

I understand that you were trying to clean up the controller code, and I agree it was very ugly, but if it worked fine and now it doesn't... better leave it as it was 😅 

The point you have to keep in mind is that the counters and options of *all* filters depend on what is currently being displayed.

For example, if I have no filters, and "Next events" are selected, the categories dropdown filters only next events:

![imagen](https://user-images.githubusercontent.com/973709/110306492-d019d100-7ff5-11eb-9607-0c03fcf1ef13.png)

But if I choose "This week", the categories dropdown filters events for just this week:

![imagen](https://user-images.githubusercontent.com/973709/110306584-e6279180-7ff5-11eb-9caf-8ac983ed70be.png)

That's how all upstream filters work, and that's how the cities one must work too.

2021-03-08 15:50 UTC, victoralmau commented
Ok, thanks for the explanation, if I have understood everything correctly it is already solved.

2021-03-10 08:01 UTC, Yajo commented
It doesn't seem so:

![imagen](https://user-images.githubusercontent.com/973709/110596067-c10e5c80-8176-11eb-9110-2d482bbbd3fb.png)

2021-03-18 07:11 UTC, joao-p-marques requested changes

2021-03-18 07:11 UTC, joao-p-marques commented on website_event_filter_city/tests/test_ui.py
> +from odoo.tests.common import HttpCase
```suggestion
from odoo.tests.common import HttpCase, tagged
```

2021-03-18 07:11 UTC, joao-p-marques commented on website_event_filter_city/tests/test_ui.py
> +
```suggestion
@tagged("post_install", "-at_install")
```

2021-03-18 07:11 UTC, joao-p-marques commented on website_event_filter_city/tests/test_ui.py
> +        )
You could simplify this:
```suggestion
        self.start_tour("/event", "website_event_filter_city", login="portal")
```
Also, adding the `login="portal"` avoids the 404 error you are getting.

2021-03-18 11:54 UTC, victoralmau commented
Tour is already fixed.
Can you check it again?

2021-03-18 14:57 UTC, joao-p-marques requested changes

2021-03-18 14:57 UTC, joao-p-marques commented on website_event_filter_city/__manifest__.py
> +    "version": "13.0.1.2.0",
```suggestion
    "version": "13.0.1.0.0",
```

2021-03-19 08:17 UTC, Yajo approved these changes
Code looks perfect now, and functional tests passed. Congratulations, this was a hard one. ✊🏼 🎉

2021-03-19 08:24 UTC, pedrobaeza approved these changes

2021-03-19 08:24 UTC, pedrobaeza commented
/ocabot merge nobump

2021-03-19 08:50 UTC, merged