[15.0][FIX] event_session: Change web_ribbon text to title to make it translatable
OCA/event pull request #358
Opened 2024-01-29 09:23 UTC by victoralmau

Change web_ribbon text to title to make it translatable

@Tecnativa

2024-01-29 09:24 UTC, chienandalu approved these changes

2024-01-29 20:42 UTC, pedrobaeza requested changes
The same about the undesired changes in the PO file.

2024-01-30 07:16 UTC, victoralmau commented
Changes done.

2024-01-30 07:18 UTC, pedrobaeza approved these changes
/ocabot merge minor

2024-01-30 07:25 UTC, merged