[16.0] [MIG] event_contact
OCA/event pull request #368
Opened 2024-04-29 10:48 UTC by edlopen

Standard migration to 16.0

MT-1840

@yajo @EmilioPascual @Shide @rafaelbn review this PR when you can.

2024-04-29 11:00 UTC, rafaelbn commented
/ocabot migration event_contact

2024-04-30 08:17 UTC, yajo approved these changes

2024-04-30 09:06 UTC, EmilioPascual approved these changes
@edlopen good job migrating this module.
Funciontal and code review.

2024-04-30 11:16 UTC, Shide approved these changes

2024-05-03 09:44 UTC, EmilioPascual commented
@edlopen can you make rebase for run tests again, thank you

2024-05-07 09:49 UTC, yajo requested changes

2024-05-07 09:49 UTC, yajo commented on event_contact/models/event_event.py
> +        self.contact_ids |= self.event_type_id.contact_ids
issue: This seems a bug to me.

```suggestion
        for one in self:
            one.contact_ids |= one.event_type_id.contact_ids
```

2024-05-08 06:43 UTC, edlopen commented on event_contact/models/event_event.py
> +        self.contact_ids |= self.event_type_id.contact_ids
Indeed!

2024-05-08 08:09 UTC, yajo approved these changes

2024-05-08 08:33 UTC, edlopen commented
Can you check it functionally @fcvalgar? Thanks!

2024-05-09 09:21 UTC, fcvalgar approved these changes
Functional review,

LGTM, thank you @edlopen 

![image](https://github.com/OCA/event/assets/17847432/6e433299-4869-4974-b7ac-26a30bd4abc5)

![image](https://github.com/OCA/event/assets/17847432/f2f0339e-a5d5-4ead-ad2f-ccb36ec0cf02)

![image](https://github.com/OCA/event/assets/17847432/c56ac9a8-c32e-49a0-892e-0f2a6e931b10)

2024-05-10 10:02 UTC, yajo commented
/ocabot merge nobump

2024-05-10 10:08 UTC, merged