[17.0][MIG] sale_order_invoicing_finished_task: Migration to version 17.0
OCA/event pull request #390
Opened 2024-07-17 10:52 UTC by juanjosesegui-tecnativa

@Tecnativa TT50120

2024-07-17 10:54 UTC, chienandalu reviewed
The name of the PR isn't correct :sweat_smile:

2024-07-17 15:32 UTC, pedrobaeza commented
Please check the red CIs, as the module doesn't even install.

2024-07-18 07:00 UTC, juanjosesegui-tecnativa commented
The module depends on partner_event, I suspect it does not install because partner_event is not in version 17.0 of OCA.

2024-07-18 07:02 UTC, chienandalu commented
You're suspicions are funded :smile: push the migration of `partner_event` so you can move forward on this one :wink:

2024-07-18 07:30 UTC, pedrobaeza commented
/ocabot migration event_registration_partner_unique

If this depends in another PR, you can do: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

2024-07-18 07:30 UTC, pedrobaeza commented
And always put in the main comment such dependency:

```
Depends on:

- [ ] partner_event: https://github.com/OCA/event/pull/382
```

2024-07-18 08:25 UTC, pedrobaeza commented
You have ignored this part of the guide:

![imagen](https://github.com/user-attachments/assets/3e66bd7b-60ac-4465-bc1d-bea12719fc96)

2024-07-19 07:14 UTC, juanjosesegui-tecnativa commented
ping @pedrobaeza @chienandalu

2024-07-19 07:28 UTC, chienandalu requested changes
Tested :+1: 

Just some small changes:

2024-07-19 07:28 UTC, chienandalu commented on event_registration_partner_unique/__manifest__.py
> +# Copyright 2024 Tecnativa - Juan José Seguí Borja
Normally for such small migration changes, better put yourself in the contributors.md file

2024-07-19 07:28 UTC, chienandalu commented on event_registration_partner_unique/views/event_event_view.xml
> +            <xpath expr="//field[@name='badge_image']" position="after">
It makes more sense after this one
```
            <xpath expr="//field[@name='create_partner']" position="after">
```

2024-07-19 08:06 UTC, juanjosesegui-tecnativa commented on event_registration_partner_unique/views/event_event_view.xml
> +            <xpath expr="//field[@name='badge_image']" position="after">
Done!

2024-07-19 08:14 UTC, chienandalu reviewed
But put yourself in contributors :sweat_smile:

2024-07-19 08:52 UTC, chienandalu approved these changes
:+1:

2024-07-19 09:02 UTC, chienandalu commented
plase review @carolinafernandez-tecnativa

2024-07-19 09:42 UTC, carolinafernandez-tecnativa commented
Please Squash administrative commits. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.

2024-07-19 10:40 UTC, juanjosesegui-tecnativa commented
@carolinafernandez-tecnativa Done!

2024-07-19 12:29 UTC, carolinafernandez-tecnativa commented
Please check again I still seing administrative commits and pre-commit auto fixes for migration is missing.

2024-07-19 16:15 UTC, carolinafernandez-tecnativa commented
Administrative commits OK

Check please this commit [MIG] event_registration_partner_unique: Migration to 17.0 is empty
and you should not change anything related to migration like this examples in pre-commit https://github.com/OCA/event/pull/390/commits/f38a2b929b798a6cced5178c4530c5f9ceca9c14#diff-858e724775ccf6c429de4636fe90cfabad2b2a15ef432cd347a8eab571e0d21dR10
https://github.com/OCA/event/pull/390/commits/f38a2b929b798a6cced5178c4530c5f9ceca9c14#diff-84d67375c5db3c3d8f88527f5e791e6be3011ae1d5e53927986dce40cfb51545R13

2024-07-22 16:25 UTC, carolinafernandez-tecnativa commented
Please Squash administrative commits. There are still some from translation that should be removed. Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate for details.

2024-07-29 12:51 UTC, carolinafernandez-tecnativa approved these changes
LGTM Thanks :)

2024-07-29 13:22 UTC, pedrobaeza commented
/ocabot merge nobump

2024-07-29 13:25 UTC, merged