[8.0][ADD] website_event_registration_seat_limit module
OCA/event pull request #56
Opened 2016-09-15 13:32 UTC by angelmoya

Add module that extend event_registration_seat_limit https://github.com/OCA/event/tree/8.0/event_registration_seat_limit to limit the quantity selector on online register process

From: https://github.com/OCA/website/pull/253

2016-09-20 10:11 UTC, Yajo commented on website_event_registration_seat_limit/views/event_template.xml
> +                    <t t-foreach="range(ticket.event_id.registration_seats_min, min(min(ticket.event_id.registration_seats_max,ticket.seats_available or 9) + 1, 10))" t-as="nb"><option t-esc="nb"/></
I think you should check if these constraints apply, because on runbot you cannot chose any quantity.

2016-09-20 10:11 UTC, yajo requested changes

2016-09-20 10:31 UTC, angelmoya commented on website_event_registration_seat_limit/views/event_template.xml
> +                    <t t-foreach="range(ticket.event_id.registration_seats_min, min(min(ticket.event_id.registration_seats_max,ticket.seats_available or 9) + 1, 10))" t-as="nb"><option t-esc="nb"/></
OK, I will check, it's not working with "Maximum of participants per registration" = 0

2016-09-30 13:20 UTC, andhit-r approved these changes
I confirm that with _Maximum of participants per registration_  = 0 user can not chose qt. But it should be fixed on event_registration_seat_limit, not here. So other than minor issue :+1:  from me

2016-09-30 13:20 UTC, andhit-r commented on website_event_registration_seat_limit/README.rst
> +For further information, please visit:
You don't need this

2016-09-30 13:20 UTC, andhit-r commented on website_event_registration_seat_limit/__openerp__.py
> +    "version": "8.0.4.0.0",
8.0.4.0.0? It should be 8.0.1.0.0

2016-09-30 14:17 UTC, Yajo commented
I'm sorry @andhit-r, but I don't agree. [The field itself explains that you should set it to 0 to ignore the setting](https://github.com/OCA/event/blob/8.0/event_registration_seat_limit/models.py#L16-L17).

2016-10-06 11:31 UTC, andhit-r requested changes
@Yajo ups sorry i did not see that. Sorry @angelmoya , you should fix https://github.com/OCA/event/pull/56#discussion_r79576994

2016-10-10 10:32 UTC, angelmoya commented
@andhit-r @Yajo It's fixed, I test it on my server, but runbot is not working to test

2016-10-10 10:34 UTC, Yajo commented
Please remember not to squash every time you patch something. Reviewing a diff is much easier than reviewing again all the code, and mergers have the squash & merge tool for most cases.

2016-10-10 10:35 UTC, pedrobaeza commented
The squash should be done at the end of the reviewing process.

2016-10-10 11:19 UTC, Yajo commented
Bots went :x:

2016-10-10 12:50 UTC, angelmoya commented
OK, pep8 fixed, and thanks for the tip

2016-10-18 07:57 UTC, Yajo commented
Still :x:

2016-10-18 08:24 UTC, rafaelbn commented
Hi @angelmoya , thanks for contribution. Please review coverage, could you add tests please? Thanks

2018-09-19 21:38 UTC, closed without merging