[9.0][event_contact] Migration to v9
OCA/event pull request #61
Opened 2016-11-07 06:59 UTC by mikevhe18

2016-11-08 03:06 UTC, rafaelbn commented
Hi @mikevhe18 , please review runbot. Thanks!!

2016-11-08 05:05 UTC, mikevhe18 commented
@rafaelbn It's done, i've made a changes. Would you kindly review this PR again ?

2016-11-16 09:52 UTC, yajo requested changes
Don't erase me, pal! :laughing: 

All will be OK once these simple changes are made :wink:

2016-11-16 09:52 UTC, Yajo commented on event_contact/tests/__init__.py
> -# © 2016 Antiun Ingeniería S.L. - Jairo Llopis
Please don't remove others' copyright, just add yours below if you want. :wink:

BTW you can change this one to `Copyright 2016 Jairo Llopis <jairo.llopis@tecnativa.com>`

2016-11-16 09:52 UTC, Yajo commented on event_contact/tests/test_event.py
> -# © 2016 Antiun Ingeniería S.L. - Jairo Llopis
Same.

2016-11-16 09:52 UTC, Yajo commented on event_contact/views/event_event_view.xml
> +        <record model="ir.ui.view" id="event_event_form_view">
Better not change XMLID if not strictly required. Complicates things for migrations.

2016-11-16 09:52 UTC, Yajo commented on event_contact/views/event_event_view.xml
>      <data>
`<odoo>`

2016-11-16 09:52 UTC, Yajo commented on event_contact/views/event_type_view.xml
> +	<data>
`<odoo>`

2016-11-16 09:52 UTC, Yajo commented on event_contact/views/event_type_view.xml
> -     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl). -->
As said before...

2016-11-16 09:52 UTC, Yajo commented on event_contact/views/event_type_view.xml
> +		<record id="event_type_form_view" model="ir.ui.view">
Same about XMLID.

2016-11-18 05:43 UTC, mikevhe18 commented
Sorry @Yajo, it's my fault. 
I already fix it.

2017-02-24 12:52 UTC, andhit-r approved these changes
:+1:

2017-02-24 13:44 UTC, pedrobaeza commented
@Yajo, please check your review now that this has been changed

2017-02-27 08:36 UTC, yajo requested changes

2017-02-27 08:36 UTC, Yajo commented on website_event_contact/views/website_event_contact.xml
> +            <xpath expr="//div[@class='col-md-4 css_noprint']" position="replace">
Wrong replacement.

You should just add the little part you need (the contacts one, right after Organizer). You are instead overwriting many things you don't need to. This means problems for sure.

2017-05-26 01:08 UTC, rafaelbn commented on website_event_contact/views/website_event_contact.xml
> +            <xpath expr="//div[@class='col-md-4 css_noprint']" position="replace">
@mikevhe18 could you review this comment please? Thanks!

2017-05-26 16:59 UTC, rafaelbn approved these changes
Functionally tested in runbot 👍 

Please @mikevhe18 review https://github.com/OCA/event/pull/61#pullrequestreview-23932398 in order to merge! thanks

2022-01-16 12:16 UTC, closed without merging