[ADD] event_kanban_view_optimized
OCA/event pull request #62
Opened 2016-11-07 17:01 UTC by antespi

Event kanban view optimized
===========================

Event kanban view computes ``is_subscribed`` field per each event and loading time
is degraded when events have many registrations. This addon removes this field
from kanban view in order to optimize loading time.

2016-11-07 17:08 UTC, pedrobaeza commented on event_kanban_view_optimized/views/event_event_view.xml
> +        <div groups="base.group_user,base.group_portal" position="replace"/>
Why this replace?

2016-11-07 19:04 UTC, antespi commented on event_kanban_view_optimized/views/event_event_view.xml
> +        <div groups="base.group_user,base.group_portal" position="replace"/>
This is the section where `is_subscribed` variable is used: https://github.com/odoo/odoo/blob/4809b572835a94543cd1f37e621a98fabec053fd/addons/event/event_view.xml#L227

2016-11-07 21:09 UTC, rafaelbn approved these changes
I've tested in production environment of a customers as in runbot there is not such an amount of events an registries.

2016-11-07 23:49 UTC, pedrobaeza approved these changes

2016-11-09 13:47 UTC, yajo requested changes

2016-11-09 13:47 UTC, Yajo commented on event_kanban_view_optimized/README.rst
> +Event kanban view computes ``is_subscribed`` field per each event and loading time
"per event" or "for each event"

2016-11-09 13:48 UTC, merged