9.0 mig event email reminder
OCA/event pull request #65
Opened 2016-11-15 22:29 UTC by cubells

Changes included:
    - Imported last updates from v8
    - Adapted to v9
    - Fix error on tests

cc @Tecnativa

2016-11-17 11:11 UTC, yajo submitted a review, later dismissed

2016-11-17 11:11 UTC, Yajo commented on event_email_reminder/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/199/8.0
9.0

2016-11-17 11:11 UTC, Yajo commented on event_email_reminder/data/event_email_reminder_data.xml
> +<data noupdate="1">
`<odoo noupdate="1">`

2016-11-17 11:11 UTC, Yajo commented on event_email_reminder/models/event.py
> +        :param int days: number of days to reminder when events star
"start"

2016-11-17 11:11 UTC, Yajo commented on event_email_reminder/data/event_email_reminder_data.xml
> +    <field name="args" eval="'(5, False, False, None)'"/>
You add 5 by default here, and 7 in the method. I think it's more consistent to have the same default in both places.

2016-11-17 11:11 UTC, Yajo commented on event_email_reminder/data/event_email_reminder_data.xml
> +    <field name="interval_type">days</field>
So everyday you get an email with next events?

Well, I guess you can change that, but seems a bit spamming default. Not blocker though.

2016-11-25 19:59 UTC, pedrobaeza requested changes

2016-11-25 19:59 UTC, pedrobaeza commented on event_email_reminder/models/event.py
> +        limit_date = datetime.strptime(
Use here `fields.Date.from_string()`

2016-11-25 19:59 UTC, pedrobaeza commented on event_email_reminder/tests/test_event_event.py
> +        date_event_1 = datetime.strptime(
Use `fields.Date.from_string`

2016-11-25 22:27 UTC, pedrobaeza commented on event_email_reminder/models/event.py
> +        limit_date = datetime.strptime(
This one still remains untouched.

2016-11-26 15:52 UTC, pedrobaeza approved these changes

2016-11-26 16:13 UTC, merged