[9.0][MIG] crm_lead_to_event_registration module
OCA/event pull request #68
Opened 2017-01-10 06:51 UTC by cubells

- Updated views
- Updated Readme

cc @Tecnativa

2017-01-10 13:25 UTC, pedrobaeza requested changes

2017-01-10 13:25 UTC, pedrobaeza commented on crm_lead_to_event_registration/wizard/crm_lead_event_pick.py
> +    lead_id = fields.Many2one(
Test this wizard.

2017-01-10 13:25 UTC, pedrobaeza commented on crm_lead_to_event_registration/models/crm_lead.py
> +            if not name:
Put here `# pragma: no cover` and this is not critical to test

2017-01-10 13:25 UTC, pedrobaeza commented on crm_lead_to_event_registration/models/crm_lead.py
> +            if self._track_subtype(['stage_id']) == "crm.mt_lead_won":
Test this and change it if XML-IDs have changed.

2017-01-10 13:26 UTC, pedrobaeza commented on crm_lead_to_event_registration/wizard/crm_lead_to_opportunity.py
> +        if not self.event_id:
Put `event_id` as required and you can remove this.

2017-01-18 05:49 UTC, cubells commented on crm_lead_to_event_registration/wizard/crm_lead_event_pick.py
> +    lead_id = fields.Many2one(
Done.

2017-01-18 05:50 UTC, cubells commented on crm_lead_to_event_registration/models/crm_lead.py
> +            if self._track_subtype(['stage_id']) == "crm.mt_lead_won":
Done tests.

2017-01-31 12:33 UTC, pedrobaeza approved these changes

2017-03-24 09:35 UTC, luismontalba approved these changes
Functionality tested on runbot

2017-03-24 09:37 UTC, merged