[9.0][MIG] event_registration_mass_mailing module
OCA/event pull request #71
Opened 2017-01-12 19:03 UTC by cubells

- Updated README
- Updated views

cc @Tecnativa

2017-03-21 08:34 UTC, luismontalba approved these changes
Tested on runbot

2017-03-21 16:32 UTC, pedrobaeza requested changes

2017-03-21 16:32 UTC, pedrobaeza commented on event_registration_mass_mailing/README.rst
> +* Add 'Action > Mass mailing to partners' button in the partner views: with this
s/partner view/registrations view

2017-03-21 16:32 UTC, pedrobaeza commented on event_registration_mass_mailing/README.rst
> +* Add 'Action > Add to mailing list' button in the partner views: with this
s/partner view/registrations view

2017-03-21 16:32 UTC, pedrobaeza commented on event_registration_mass_mailing/__openerp__.py
> +    'version': '9.0.1.1.0',
Why not 9.0.1.0.0?

2017-03-21 16:32 UTC, pedrobaeza commented on event_registration_mass_mailing/models/email_template.py
> +        if 'arch' in res:
You can save one indentation making:
```
if 'arch' not in res:
    return res
doc = ...

2017-03-21 16:32 UTC, pedrobaeza commented on event_registration_mass_mailing/models/email_template.py
> +                if domain:
The same:
```
if not domain:
    continue
domain = ...
```

2017-03-30 18:02 UTC, chienandalu approved these changes
tested on runbot

2017-03-30 23:05 UTC, pedrobaeza approved these changes

2017-03-30 23:06 UTC, merged

2017-03-31 05:01 UTC, rafaelbn commented
Please @cubells review comments. Functionally module is OK 👍