[ADD][WIP] event_session: New module
OCA/event pull request #75
Opened 2017-04-17 17:03 UTC by chienandalu

This module allows to create sessions associated with events.

2017-04-17 17:13 UTC, chienandalu commented
cc @Tecnativa

2017-04-18 09:04 UTC, sergio-teruel requested changes

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/README.rst
> +* Go to an event a use the sessions wizard to create all your sessions according to a schedule.
s/a/and

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/README.rst
> +* Go to an event a use the sessions wizard to create all your sessions according to a schedule.
s/all your sessions/event

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/README.rst
> +* TODO: Improve hours constraints
Why this features is in roadmap?

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/__manifest__.py
> +# Part of Odoo. See LICENSE file for full copyright and licensing details.
Fix copyrigth according to https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event.py
> +        ondelete='set null',
'set null' is the deafult value so is not necessary,but if you remove an event session that has registrations you will lose the data relative to session. Really do you want that?

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event.py
> +        compute='_compute_sessions_count'
Add string attribute and put a comma at the end.

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event_session.py
> +        help="Each session will start at this time (in the event's timezone)",
You are in session record not in wizard, so this start time is only one.
s/Each session will/Session start time

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event_session.py
> +        help="Each session will end at this time",
the same...

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event_session.py
> +        for session in self:
Keep conventions as:
```python
  # Constraints and onchanges
    @api.constrains('seats_max', 'seats_available')
    def _check_seats_limit(self):
        ...
```
Take a look https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/models/event_session.py
> +        for session in self:
Same

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/views/event_session_view.xml
> +</odoo>
Add blank line

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/views/event_view.xml
> +</odoo>
Add blank line

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +        default='void',
If you want a temporaly name for field you must be use **default='/'**

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +             "Sessions will be generated from this date",
This related field must be readonly

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +             "Sessions will be generated up to this date",
This related field must be readonly

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +             "Sessions will be generated up to this date",
Readonly

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +            (("event_id", "=", self.event_id.id),
domain format is a list that contains tuples as [('a', '=', 1), ()...]

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +        data.update(values)
If you do a method as "_prepare_session_values()" that return a dictionary other modules will can extend this method

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +
Remove white blank lines

2017-04-18 09:04 UTC, sergio-teruel commented on event_session/wizards/wizard_event_session.py
> +
Remove white blank lines

2017-04-18 09:05 UTC, sergio-teruel commented
don't forget translations and tests :smile:

2017-04-18 10:03 UTC, chienandalu commented on event_session/models/event.py
> +        ondelete='set null',
Yes, I think it's better to keep the assistant even if the associated session is deleted.

2017-05-03 11:11 UTC, sergio-teruel commented on event_session/tests/test_session.py
> +        with self.assertRaises(ValidationError), self.cr.savepoint():
Make test for all created methods and all cases..

2017-05-23 07:48 UTC, Yajo commented on event_session/models/event.py
> +        ondelete='set null',
If that's the case, just remove the line as @sergio-teruel said please

2017-05-23 08:15 UTC, yajo requested changes
Date programming is a bit weird always, but I feel you are reinventing some wheels here. Check comments.

2017-05-23 08:15 UTC, yajo commented on event_session/wizards/wizard_event_session.py
> +            "name": "{} {} - {}".format(
You must use a Unicode string for using `.format`

2017-05-23 08:15 UTC, yajo commented on event_session/wizards/wizard_event_session.py
> +                         strptime(values["date"], "%Y-%m-%d %H:%M:%S")),
All of this makes not much sense IMHO. You should just use the current context lang's settings instead of inventing all of this.

Hint: `self.env["res.lang"]._lang_get(self.env.lang)` fields: `date_format` and `time_format`.

2017-05-23 08:15 UTC, Yajo commented on event_session/wizards/wizard_event_session.py
> +                "%02d:%02d" % divmod(values["end_time"]*60, 60),
I guess this works, although it is a little bit hacky to read. Once you have `date` and `lang` from above, you can do this to get it perfect:

`strftime(lang.time_format, date + datetime.timedelta(seconds=values["start_time"])`

2017-05-23 08:15 UTC, Yajo commented on event_session/wizards/wizard_event_session.py
> +                "%02d:%02d" % divmod(values["end_time"]*60, 60)),
Possibly some of the above clues will make this better too.

2017-05-23 08:15 UTC, Yajo commented on event_session/wizards/wizard_event_session_view.xml
> +                or
Drop this line.

2017-05-23 08:15 UTC, Yajo commented on event_session/models/event_session.py
> +    _name = 'event.session'
What's the point on creating this model instead of using upstream `event.track`?

2017-05-23 10:55 UTC, chienandalu commented on event_session/wizards/wizard_event_session.py
> +            "name": "{} {} - {}".format(
Well, it crashes if I do so whenever a unicode string is passed.

2017-05-23 10:57 UTC, chienandalu commented on event_session/wizards/wizard_event_session.py
> +                         strptime(values["date"], "%Y-%m-%d %H:%M:%S")),
Well, but I really want the session name formatted like that for usability's sake

2017-05-23 11:02 UTC, chienandalu commented on event_session/wizards/wizard_event_session.py
> +                "%02d:%02d" % divmod(values["end_time"]*60, 60),
Yes, a rework could be made with all the hours and dates management.

2017-05-23 16:23 UTC, chienandalu commented on event_session/models/event_session.py
> +    _name = 'event.session'
We wanted something like pseudo-events. Another approach was to group events with something like a super-event, but was discarded.

2017-05-23 16:28 UTC, pedrobaeza commented on event_session/models/event_session.py
> +    _name = 'event.session'
Tracks have another goal: they are part of an event. You can even have an event with several tracks and several sessions.

2017-05-24 09:17 UTC, Yajo commented on event_session/models/event_session.py
> +    _name = 'event.session'
Hmm I get it. It's like when you have a training of 5 tracks (monday to friday) but you repeat the training 3 weeks, right?


Interesting, although IMHO you should document more explicitly this addon's purpose, or further reviewers will wonder about this...

2017-05-24 09:23 UTC, pedrobaeza commented on event_session/models/event_session.py
> +    _name = 'event.session'
Yeah, exactly about both points.

2017-05-25 20:55 UTC, pedrobaeza commented on event_session/README.rst
> +Create and assign sessions to events
above line missing

2017-05-26 16:40 UTC, rafaelbn commented
Travis still fails cc @sergio-teruel @chienandalu @pedrobaeza

2017-06-20 17:01 UTC, pedrobaeza requested changes

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/README.rst
> +Create and assign sessions to events
The line above is still missing

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +        if self.sessions_count < 1:
This needs a `for` loop

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +        if self.sessions_count < 1:
Use `if not event.session_ids:` instead (being `event` the variable for each record.

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +            event.session_ids = [(0, 0, {
This shouldn't be needed

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +        ondelete='set null',
This should be `ondelete='restrict'`. You cannot remove a session if you have registration on it.

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +        for registration in self:
Save one `if` putting `for registration in self.filtered('session_id'):`

2017-06-20 17:01 UTC, pedrobaeza commented on event_session/models/event.py
> +                super(EventRegistration, self).confirm_registration()
You are passing `self` instead of `reg` to super. Take much care with this!

2017-06-20 18:40 UTC, pedrobaeza commented
I have added a commit for using the new SQL view and that should fix also the need for at least one session.

2017-06-29 16:42 UTC, chienandalu commented
@Yajo @pedrobaeza @sergio-teruel This is ready for review

2017-06-30 07:47 UTC, yajo requested changes

2017-06-30 07:47 UTC, Yajo commented on event_session/README.rst
> +according to a given schedule.
Prefix with 2 spaces or formatting will break

2017-06-30 07:47 UTC, Yajo commented on event_session/models/event.py
> +                    (1 if registration.state == 'draft' else 0)):
Are you checking if we have less than zero available seats? Like -1? 🤔

2017-06-30 07:47 UTC, Yajo commented on event_session/tests/test_session.py
> +    # TODO: Revisar test
🗑

2017-06-30 09:22 UTC, chienandalu commented on event_session/models/event.py
> +                    (1 if registration.state == 'draft' else 0)):
I can't recall why this was implemented like this. I've rewritten it .

2017-06-30 09:23 UTC, chienandalu commented on event_session/tests/test_session.py
> +    # TODO: Revisar test
I got to fix it

2017-06-30 10:11 UTC, yajo approved these changes

2017-07-29 10:25 UTC, pedrobaeza requested changes
And finally make a proper squash of all the commits.

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_mail.py
> +                date_open_datetime = date_open and datetime.strptime(
Use `fields.Datetime.from_string`

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/__manifest__.py
> +    'depends': ['event', 'event_mail'],
I would like to avoid `event_mail` dependency here.

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_session.py
> +        for session in self:
This is not needed, as by default all fields are reset to their default values (0 in this case).

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_session.py
> +            query = """
Can you use `read_group` instead of this ugly SQL?

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_session.py
> +                session.date_begin_located = False
No need to assign default value, so instead just do `for session in self.filtered('date_begin'):`

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_session.py
> +                session.date_end_located = False
The same

2017-07-29 10:25 UTC, pedrobaeza commented on event_session/models/event_session.py
> +        self.seats_min = self.event_id.seats_min
Use `self.update` for making only one write operation (in case this is called outside an UI onchange itself).

2017-11-17 23:36 UTC, rafaelbn commented
Please @chienandalu review comment. This module is in production for a long time we should be able to merge. I'm testing it

2017-11-17 23:38 UTC, rafaelbn approved these changes
Functionally tested 👍 . Please @sergio-teruel last review here. Thanks

2017-11-22 01:01 UTC, rafaelbn commented
Hi @chienandalu please could `And finally make a proper squash of all the commits.` to make @pedrobaeza happy and merge this? 😄 👍

2017-11-22 07:37 UTC, chienandalu commented
There's quite a mess o commits from @pedrobaeza @sergio-teruel and myself :sweat_smile: Should I squash them all together or do I try to keep the closer to a history?

2017-11-22 08:19 UTC, pedrobaeza commented
Group them by author/logic

2017-11-22 08:24 UTC, chienandalu commented
Yes, the problem is that they are very mixed up in both ways. I'll try my best :)

2017-12-21 12:45 UTC, chienandalu commented
@pedrobaeza Now rebased (sorry for the delay)

2017-12-21 15:53 UTC, pedrobaeza approved these changes

2017-12-21 15:53 UTC, merged