[MIG] event_registration_mass_mailing: Migration to 10.0
OCA/event pull request #80
Opened 2017-06-14 15:30 UTC by chienandalu

cc @Tecnativa

2017-06-15 07:18 UTC, yajo requested changes
Please fix Travis.

2017-06-19 00:48 UTC, pedrobaeza requested changes
Change website to Tecnativa's one in the manifest and please try to improve test coverage.

2017-06-22 18:20 UTC, chienandalu commented
@pedrobaeza I'm not sure about how to get inside the uncovered code from the test :confused:

2017-06-23 12:38 UTC, yajo approved these changes

2017-06-23 15:00 UTC, pedrobaeza approved these changes

2017-06-23 15:04 UTC, merged