[MIG] website_event_share: Migration to 10.0
OCA/event pull request #82
Opened 2017-06-22 12:01 UTC by chienandalu

Event Share
===========

This module brings the users the possibility to globally enable/disable a share
links block that will be displayed in every event post.

cc @Tecnativa

2017-06-22 12:56 UTC, pedrobaeza approved these changes
Minor detail

2017-06-22 12:56 UTC, pedrobaeza commented on website_event_share/README.rst
> +for each event
Indent this 2 spaces.

2017-06-22 13:54 UTC, chienandalu commented
@pedrobaeza Changes done

2017-06-23 07:22 UTC, yajo requested changes
A couple of things to improve.

OTOH, are you really sure you want to maintain this addon? No offense, but Odoo 10 already has a "Share" snippet that does basically the same (well, you have to drag and drop once per event, but also lets the user choose where to put it):

![captura de pantalla de 2017-06-23 09-19-00](https://user-images.githubusercontent.com/973709/27470672-5e5e959a-57f5-11e7-8abb-9958679ebcd6.png)

IMHO I feel it's better to train users to use core tools than adding addons as this one.

2017-06-23 07:22 UTC, Yajo commented on website_event_share/views/website_event.xml
> +                    <a href="mailto:?body={url}&amp;subject={title}"><i class="fa fa-envelope-o"> </i></a>
Any chances we can reuse [`website.s_share`](https://github.com/odoo/odoo/blob/668926ff4f75a66634991282ffabefc66aadf924/addons/website/views/snippets.xml#L267-L278) instead?

2017-06-23 07:22 UTC, Yajo commented on website_event_share/views/website_event.xml
> +        <xpath expr="//h4[@t-field='event.address_id']" position="after">
How come you use xpath in a template without `inherit_id`?

2017-06-23 07:44 UTC, pedrobaeza commented
@Yajo the module should be maintained to assure it always appear, but as you have said, maybe this can reuse some of the standard logic.

2017-06-26 07:45 UTC, chienandalu commented
@Yajo Changes done

2017-06-26 07:58 UTC, yajo approved these changes
Code review seems OK.

2017-07-03 08:29 UTC, yajo requested changes

2017-07-03 08:29 UTC, Yajo commented on website_event_share/views/website_event.xml
> +    <template id="event_share" name="Share Button" inherit_id="website_event.event_details" active="False" customize_show="True">
Remove `active=False` to get the addon enabled by default when installed.

2017-07-03 09:02 UTC, chienandalu commented
@Yajo Done

2017-07-03 09:12 UTC, yajo approved these changes

2017-07-03 09:16 UTC, pedrobaeza commented
@chienandalu squash your commits and I'll merge

2017-07-03 09:28 UTC, chienandalu commented
@pedrobaeza Done

2017-07-03 09:45 UTC, merged

2017-09-22 07:28 UTC, yelizariev commented
Is it correct description in manifest?
+    'summary': 'Add contacts to event',

2017-09-22 07:30 UTC, pedrobaeza commented
Obviously not (copy/paste error). Fixed in https://github.com/OCA/event/commit/72900bf4c21a3dd31144d58fe52f72ca70f1ec1b

2017-09-22 07:36 UTC, yelizariev commented
@pedrobaeza you fixed in 2 minutes after reporting! Thank you :smile_cat: