[MIG] event_project: Migration to 10.0
OCA/event pull request #86
Opened 2017-06-23 15:01 UTC by chienandalu

Plan events through projects
============================

This module allows you to assign a project to an event. This project will
inherit its event's name an its due date will be set as the event's begining
date.

cc @Tecnativa

2017-06-30 10:56 UTC, pedrobaeza commented
Please rebase and make sure OCA/project is on oca_dependencies.txt

2017-06-30 15:06 UTC, chienandalu commented
@pedrobaeza All green now

2017-06-30 15:32 UTC, pedrobaeza approved these changes

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/README.rst
> +* Create a project or duplicate an existing one that fits your needs.
Use numbered bullets with `#.`

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/README.rst
> +* The project will inherit its
This sentence is cut.

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/README.rst
> +This module allows you to assign a project to an event. This project will
The idea is to make a copy of the project, not to use it.

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/__manifest__.py
>      "author": "Antiun Ingeniería S.L., "
Remove Antiun also

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/wizard/project_template_wizard.py
> -class ProjectTemplateWizard(models.TransientModel):
Why do you remove this wizard? Just drop the domain for "template" projects, but don't remove it.

2017-06-30 15:32 UTC, pedrobaeza commented on event_project/views/event_event_view.xml
> -        <page string="Event Details" position="after">
We need to add a module _event_project_timesheet_ that restores back the equivalent of this page.

2017-06-30 15:33 UTC, pedrobaeza requested changes

2017-06-30 15:33 UTC, pedrobaeza commented on event_project/README.rst
> +* The project will inherit its
This text is still half

2017-06-30 15:33 UTC, pedrobaeza commented on event_project/README.rst
> +* Create a project or duplicate an existing one that fits your needs.
Don't remove the feature of making a project copy

2017-08-07 14:53 UTC, pedrobaeza commented
@chienandalu please review my last comments

2017-08-08 07:54 UTC, chienandalu commented
@pedrobaeza Changes done

2017-08-09 18:13 UTC, chienandalu commented
@pedrobaeza I'm triying to recover the project copy feature but I'm having issues on event write().
Everything goes fine until here (https://github.com/Tecnativa/event/blob/17a4ace53f5e5681e0df3ec50d8eeaa9470840b6/event_project/models/event_event.py#L73). There is a copy of the project and it's linked to the event, but once it goes out from write(), event.project_id resets to its previous value :confused: 

Any ideas?

2017-08-10 07:34 UTC, pedrobaeza commented on event_project/models/event_event.py
> +    task_ids = fields.One2many(
A related `One2many` without `readonly`??!! I don't think so... This for sure is causing troubles.

2017-08-10 09:08 UTC, pedrobaeza commented
The related one2many is still there. You can't make a related one2many AFAIK.

2017-08-14 08:00 UTC, pedrobaeza commented
Check conflicting files also.

2017-08-14 15:56 UTC, chienandalu commented
@pedrobaeza Conflicts resolved but still having the same issue:

Here everything is set ok: https://github.com/Tecnativa/event/blob/17a4ace53f5e5681e0df3ec50d8eeaa9470840b6/event_project/models/event_event.py#L73
Here Odoo changes it back: https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L909

2017-08-15 12:05 UTC, pedrobaeza approved these changes

2017-08-15 12:07 UTC, pedrobaeza commented
In this case, the problem is not real, but you have to force a refresh of the record. Check d38d90dd3e8b24bf8bf3d6a6f101d715fae98064 for the solution (call `refresh`), and other patches to avoid multi-record problems (take always into account that any button/method with `@api.multi` can be called with multiple records).

2017-08-15 12:08 UTC, pedrobaeza commented
@luismontalba please review

2017-08-16 07:24 UTC, chienandalu commented
Thanks @pedrobaeza :slightly_smiling_face:

2017-08-16 07:48 UTC, luismontalba approved these changes
Tested on runbot

2017-08-16 08:03 UTC, merged