[IMP] partner_event: forbid partner deletion if it has event registrations
OCA/event pull request #94
Opened 2017-10-23 18:01 UTC by chienandalu

- If the partner has event registrations it won't be allowed to delete it.

cc @Tecnativa

2017-10-23 21:37 UTC, pedrobaeza requested changes
Change module version

2017-10-23 21:37 UTC, pedrobaeza commented on partner_event/tests/test_event_registration.py
> +        with self.assertRaises(MissingError):
Do `self.assertFalse(partner3.exists())` instead

2017-10-23 21:37 UTC, pedrobaeza commented on partner_event/tests/test_event_registration.py
> +            'name': 'unregistered partner'
Always comma at the end for not having a 2 lines diff in the future

2017-10-23 21:37 UTC, pedrobaeza commented on partner_event/models/res_partner.py
> +        if self.registration_count > 0:
No need of `> 0`

2017-10-23 21:37 UTC, pedrobaeza commented on partner_event/models/res_partner.py
> +        if self.registration_count > 0:
But I think you can just put on the one2many ondelete='restrict'. I'm not sure if it's going to work, but you have tests for that.

2017-10-24 09:15 UTC, chienandalu commented
@pedrobaeza Changes done

2017-10-24 14:57 UTC, chienandalu commented
@rafaelbn Please review

2017-10-24 17:33 UTC, pedrobaeza approved these changes

2017-10-24 17:33 UTC, pedrobaeza commented
Indeed the best option is to restrict on the many2one instead.

2017-10-24 23:19 UTC, rafaelbn commented
@chienandalu This Improvement was already done in v8 in : https://github.com/OCA/event/commit/9dc9d383856b7dff5b9db938797e4cb9e1a2a91c

But that changes were lost in v9 migration and in v10 migration.

This means that we loose also the code refactoring that @pedrobaeza did

I think we should recover what it was done

2017-10-25 08:21 UTC, chienandalu commented
@rafaelbn Changes done

2017-10-26 00:31 UTC, rafaelbn commented on partner_event/README.rst
>  * Partner column is visible on registration one2many list inside the event.
This is wrong @chienandalu as this list doesn't exist any more

2017-10-26 00:43 UTC, rafaelbn approved these changes
I've tested "partner_event: forbid partner deletion if it has event registrations" and it works fine 👍 But I have found some inconsistencies in this module. We can merge this IMP and make a FIX for the other staff.

2017-10-26 00:43 UTC, rafaelbn commented on partner_event/models/event_registration.py
>                  # Create partner
@chienandalu hello! This doesn't work if you register in a free event. The partner is not created. Should we fix it? I've seen two different behavior for the same workflow (registering a partner) depending if the register is executed in the backend or in the website

2017-10-26 11:31 UTC, yajo approved these changes
Some non-blockings, code OK

2017-10-26 11:31 UTC, Yajo commented on partner_event/__manifest__.py
> +    'version': '10.0.1.0.1',
I'm not sure, but I think this should be `10.0.1.1.0`, since this is a new feature.

2017-10-26 11:31 UTC, Yajo commented on partner_event/tests/test_event_registration.py
> +        # Create a brand new partner and delete it
I think it makes more sense to delete `partner_01` registrations and then try to delete it again, for the test purposes.

2017-11-17 23:30 UTC, rafaelbn commented
Please @chienandalu rebase to check of all goes green, thanks!

2017-11-22 01:02 UTC, merged